### ISSUE TITLE
Faces do not render behind a transparent texture

### ISSUE THREAD

**Issue by KnightMiner** [MrCrayfish/ModelCreator#36]
Currently, transparent textures are only transparent to the background, other faces are invisible behind that one, which kinda defeats the point in my opinion.

**Comment by mateuszdrwal** [comment]
i dont get what you mean, what about some screenshots?

**Comment by KnightMiner** [comment]
Basically through a transparent section of an image, all other objects are not rendered.

[Screenshot](https://cloud.githubusercontent.com/assets/12155288/7379239/29bb57ae-edb9-11e4-8bd2-2eb0748f7527.png)

**Comment by Phallopode** [comment]
It's a limitation of how the rendering engine is configured in minecraft, am I right ? Some sort of culling. I guess I read in a forum that it was possible to overcome this in changing the order of rendering of the cube in the .json file. Interverting them ine the code. Although I never tried myself and they're was maybe a subtility.

**Comment by mateuszdrwal** [comment]
phallopode: it is not minecraft that is the problem, because then this issue would not be here. its the program not rendering it, and it is a program bug.

qith that being said, im pretty sure its fixed now and you can close the issue KnightMiner
![image](https://cloud.githubusercontent.com/assets/11805733/7751950/0ed455c2-ffdd-11e4-8b72-8611f95cd5e1.png)

**Comment by C1ffisme** [comment]
![Screenshot_2020-03-14_19-02-46](https://user-images.githubusercontent.com/9893266/76692581-8555bb00-6626-11ea-9986-1b88f2a8a198.png)

I'm still getting this with version 0.7.0. I'm also experiencing [this](https://github.com/MrCrayfish/ModelCreator/issues/121) as I use Linux.
